name: wechat
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugun: "^0.2.1+2"
  date_format: "^1.0.4"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

